/**
 */
package org.dataflowanalysis.privacy.consent_model.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.dataflowanalysis.privacy.consent_model.util.Consent_modelAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Consent_modelItemProviderAdapterFactory extends Consent_modelAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Consent_modelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.DataItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataItemItemProvider dataItemItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.DataItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataItemAdapter() {
		if (dataItemItemProvider == null) {
			dataItemItemProvider = new DataItemItemProvider(this);
		}

		return dataItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.DataState} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataStateItemProvider dataStateItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.DataState}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataStateAdapter() {
		if (dataStateItemProvider == null) {
			dataStateItemProvider = new DataStateItemProvider(this);
		}

		return dataStateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.UserDataCombination} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserDataCombinationItemProvider userDataCombinationItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.UserDataCombination}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserDataCombinationAdapter() {
		if (userDataCombinationItemProvider == null) {
			userDataCombinationItemProvider = new UserDataCombinationItemProvider(this);
		}

		return userDataCombinationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.ConsentOption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConsentOptionItemProvider consentOptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.ConsentOption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConsentOptionAdapter() {
		if (consentOptionItemProvider == null) {
			consentOptionItemProvider = new ConsentOptionItemProvider(this);
		}

		return consentOptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.Role} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleItemProvider roleItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.Role}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleAdapter() {
		if (roleItemProvider == null) {
			roleItemProvider = new RoleItemProvider(this);
		}

		return roleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.ConsentModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConsentModelItemProvider consentModelItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.ConsentModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConsentModelAdapter() {
		if (consentModelItemProvider == null) {
			consentModelItemProvider = new ConsentModelItemProvider(this);
		}

		return consentModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.RoleLabelType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleLabelTypeItemProvider roleLabelTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.RoleLabelType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleLabelTypeAdapter() {
		if (roleLabelTypeItemProvider == null) {
			roleLabelTypeItemProvider = new RoleLabelTypeItemProvider(this);
		}

		return roleLabelTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.RoleLabel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleLabelItemProvider roleLabelItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.RoleLabel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleLabelAdapter() {
		if (roleLabelItemProvider == null) {
			roleLabelItemProvider = new RoleLabelItemProvider(this);
		}

		return roleLabelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.ConsentLabelType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConsentLabelTypeItemProvider consentLabelTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.ConsentLabelType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConsentLabelTypeAdapter() {
		if (consentLabelTypeItemProvider == null) {
			consentLabelTypeItemProvider = new ConsentLabelTypeItemProvider(this);
		}

		return consentLabelTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.dataflowanalysis.privacy.consent_model.ConsentLabel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConsentLabelItemProvider consentLabelItemProvider;

	/**
	 * This creates an adapter for a {@link org.dataflowanalysis.privacy.consent_model.ConsentLabel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConsentLabelAdapter() {
		if (consentLabelItemProvider == null) {
			consentLabelItemProvider = new ConsentLabelItemProvider(this);
		}

		return consentLabelItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (dataItemItemProvider != null)
			dataItemItemProvider.dispose();
		if (dataStateItemProvider != null)
			dataStateItemProvider.dispose();
		if (userDataCombinationItemProvider != null)
			userDataCombinationItemProvider.dispose();
		if (consentOptionItemProvider != null)
			consentOptionItemProvider.dispose();
		if (roleItemProvider != null)
			roleItemProvider.dispose();
		if (consentModelItemProvider != null)
			consentModelItemProvider.dispose();
		if (roleLabelTypeItemProvider != null)
			roleLabelTypeItemProvider.dispose();
		if (roleLabelItemProvider != null)
			roleLabelItemProvider.dispose();
		if (consentLabelTypeItemProvider != null)
			consentLabelTypeItemProvider.dispose();
		if (consentLabelItemProvider != null)
			consentLabelItemProvider.dispose();
	}

}
