#

pluginName = org.dataflowanalysis.privacy.consentmodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_DataItem_type = Data Item
_UI_DataState_type = Data State
_UI_UserDataCombination_type = User Data Combination
_UI_ConsentOption_type = Consent Option
_UI_Role_type = Role
_UI_ConsentModel_type = Consent Model
_UI_RoleLabelType_type = Role Label Type
_UI_ConsentLabelType_type = Consent Label Type
_UI_RoleLabel_type = Role Label
_UI_ConsentLabel_type = Consent Label
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_DataItem_state_feature = State
_UI_DataItem_name_feature = Name
_UI_DataState_name_feature = Name
_UI_DataState_notRelatableWith_feature = Not Relatable With
_UI_UserDataCombination_members_feature = Members
_UI_ConsentOption_requires_feature = Requires
_UI_ConsentOption_excludes_feature = Excludes
_UI_ConsentOption_name_feature = Name
_UI_ConsentOption_allowsFor_feature = Allows For
_UI_Role_requires_feature = Requires
_UI_Role_allows_feature = Allows
_UI_Role_name_feature = Name
_UI_ConsentModel_data_states_feature = Data states
_UI_ConsentModel_roleLabelType_feature = Role Label Type
_UI_ConsentModel_consentLabelType_feature = Consent Label Type
_UI_RoleLabelType_labels_feature = Labels
_UI_ConsentLabelType_labels_feature = Labels
_UI_RoleLabel_role_feature = Role
_UI_ConsentLabel_consentOption_feature = Consent Option
_UI_Unknown_feature = Unspecified

_UI_ConsentModel_dataItems_feature = Data Items
_UI_DataItemLabelType_type = Data Item Label Type
_UI_DataItemLabel_type = Data Item Label
_UI_StatefulItem_type = Stateful Item
_UI_ConsentModel_dataItemLabelType_feature = Data Item Label Type
_UI_DataItemLabelType_labels_feature = Labels
_UI_DataItemLabel_dataItem_feature = Data Item
_UI_StatefulItem_state_feature = State
_UI_StatefulItem_item_feature = Item
