<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="consent_model" nsURI="http://www.dataflowanalysis.org/consent_model"
    nsPrefix="consent_model">
  <eClassifiers xsi:type="ecore:EClass" name="DataItem" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
        eType="#//DataState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataState" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notRelatableWith" upperBound="-1"
        eType="#//DataState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDataCombination" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//DataItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsentedFunctionality" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//ConsentedFunctionality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludes" upperBound="-1"
        eType="#//ConsentedFunctionality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowsFor" upperBound="-1"
        eType="#//UserDataCombination" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//ConsentedFunctionality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allows" upperBound="-1"
        eType="#//ConsentedFunctionality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsentModel" eSuperTypes="platform:/plugin/tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalities" upperBound="-1"
        eType="#//ConsentedFunctionality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_states" upperBound="-1"
        eType="#//DataState" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
