#

pluginName = org.dataflowanalysis.privacy.privacymodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_DataItem_type = Data Item
_UI_DataState_type = Data State
_UI_UserDataCombination_type = User Data Combination
_UI_Functionality_type = Functionality
_UI_Role_type = Role
_UI_PrivacyModel_type = Privacy Model
_UI_RoleLabelType_type = Role Label Type
_UI_FunctionalityLabelType_type = Functionality Label Type
_UI_RoleLabel_type = Role Label
_UI_FunctionalityLabel_type = Functionality Label
_UI_DataItemLabelType_type = Data Item Label Type
_UI_DataItemLabel_type = Data Item Label
_UI_StatefulItem_type = Stateful Item
_UI_DataStateLabelType_type = Data State Label Type
_UI_DataStateLabel_type = Data State Label
_UI_DataContextLabelType_type = Data Context Label Type
_UI_DataContextLabel_type = Data Context Label
_UI_DataContext_type = Data Context
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_DataState_notRelatableWith_feature = Not Relatable With
_UI_UserDataCombination_members_feature = Members
_UI_Functionality_requires_feature = Requires
_UI_Functionality_excludes_feature = Excludes
_UI_Functionality_allowsFor_feature = Allows For
_UI_Role_alwaysAllows_feature = Always Allows
_UI_Role_optionallyAllows_feature = Optionally Allows
_UI_PrivacyModel_roleLabelType_feature = Role Label Type
_UI_PrivacyModel_functionalityLabelType_feature = Functionality Label Type
_UI_PrivacyModel_dataItemLabelType_feature = Data Item Label Type
_UI_PrivacyModel_dataStateLabelType_feature = Data State Label Type
_UI_PrivacyModel_dataContextLabelType_feature = Data Context Label Type
_UI_RoleLabelType_labels_feature = Labels
_UI_FunctionalityLabelType_labels_feature = Labels
_UI_RoleLabel_role_feature = Role
_UI_FunctionalityLabel_functionality_feature = Functionality
_UI_DataItemLabelType_labels_feature = Labels
_UI_DataItemLabel_dataItem_feature = Data Item
_UI_StatefulItem_state_feature = State
_UI_StatefulItem_item_feature = Item
_UI_StatefulItem_context_feature = Context
_UI_DataStateLabelType_labels_feature = Labels
_UI_DataStateLabel_dataState_feature = Data State
_UI_DataContextLabelType_labels_feature = Labels
_UI_DataContextLabel_dataContext_feature = Data Context
_UI_Unknown_feature = Unspecified

